export const PATHS = {
  login: "/",
  recover_account: "/recuperar-cuenta",
  reset_password: "/restablecer-acceso",
  panel: "/panel",
  products: "/productos",
  users: "/usuarios",
  stores: "/expendios",
  sales: "/ventas",
  factories: "/plantas",
  deliveries: "/repartos",
  inventories: "/inventarios",
  loadingPanel: "/cargando",
  categories: "/categorias",
  presentations: "/presentaciones",
  gallery: "/galeria",
  faqs: "/faq",
  departments: "/departamentos",
  brands: "/marcas",
  retailers: "/retailers"
} as const
