name: Check PR Source Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify if source branch is dev
        run: |
          echo "Rama de origen: ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "ERROR: Only pull requests from the 'dev' branch are allowed."
            exit 1
          fi
